#!/bin/bash
function check_service() {
    /etc/init.d/$1 status
    if [ $? -ne 0 ]; then
        /etc/init.d/$1 start

        mail -s "[ecard] service $1 check failed on `hostname`" reportitnow@gewu.me <<<EOF
Time: `date`
Token: `viewtoken`
Hostname: `hostname`
Service: $1
Log last lines: $(tail /opt/gewuit/rfid/log/$1.log -n 50)
        EOF
    fi
}

if [ `hostname` == "master" ]; then
    check_service merger
fi
check_service receiver
