#!/bin/bash
# interactive deploy script

echo "===== Install RFID base station ====="

echo -n "Input vendor (e.g. default, mulandianzi): "
read vendor
if [ ! -z "$vendor" ] && [ "$vendor" != "default" ] && [ "$vendor" != "mulandianzi" ]; then
    echo 'Only default and mulandianzi is supported'
fi

echo -n "Is it [master] or [slave]? "
read target
if [ "$target" == "master" ]; then
    echo -n "School token: "
    read token
    sudo /home/pi/rfid-base-station/deploy/deploy.sh master $token $vendor
elif [ "$target" == "slave" ]; then
    echo -n "School token: "
    read token
    sudo /home/pi/rfid-base-station/deploy/deploy.sh slave $token $vendor
else
    echo 'Please input "master" or "slave"'
fi
