#!/bin/bash
HOST="pi@shi6.com"
rsync -a --remove-source-files --exclude merger.log --exclude receiver.log /opt/gewuit/rfid/log/ $HOST:ecard-log/`viewtoken`/
ssh $HOST ./log-update-trigger `viewtoken`
